# Generated by Django 5.0.1 on 2024-01-27 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abhaNumber', models.CharField(max_length=255)),
                ('aadharNumber', models.CharField(max_length=255)),
                ('centerName', models.CharField(max_length=255)),
                ('birthYear', models.CharField(blank=True, max_length=4, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('fatherHusbandName', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('maritalStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('subCaste', models.CharField(blank=True, max_length=50, null=True)),
                ('house', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pinCode', models.CharField(blank=True, max_length=10, null=True)),
                ('medication', models.CharField(blank=True, max_length=3, null=True)),
                ('bloodTransfusion', models.CharField(blank=True, max_length=3, null=True)),
                ('familyHistory', models.CharField(blank=True, max_length=3, null=True)),
                ('image', models.TextField(blank=True, max_length=500000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
