# Generated by Django 5.0.1 on 2024-02-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthRecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
