# Generated by Django 5.0.1 on 2024-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthRecords', '0003_healthrecord_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='image',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
