# Generated by Django 5.0.1 on 2024-01-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthRecords', '0003_healthrecord_birthyear_healthrecord_bloodtransfusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='image',
            field=models.TextField(blank=True, max_length=500000, null=True),
        ),
    ]
