# Generated by Django 5.0.1 on 2024-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthRecords', '0004_alter_healthrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='image',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
